name: Blog latest data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '6, 23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Run scrapers
      run: python virologyblogxlml.py
    - name: Write to CSV file
    - uses: gr2m/write-csv-file-action@v1.0.0
      with:
        path: virology_blog/virology_blog.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
